import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:gastrobluecheckapp/data/repo/processassetdao_repository.dart';

class HotProcessSubmitCubit extends Cubit {
  HotProcessSubmitCubit() : super(0);
  var HPRepo = ProcessAssetDaoRepository();

  Future<void> hotProcessSubmit(
    String asset_name,
    String user_name,
    int quantity,
    double first_temperature,
    double banket_temperature_one,
    double banket_temperature_two,
    double banket_temperature_three,
    double banket_temperature_four,
    String banket_date_one,
    String banket_date_two,
    String banket_date_three,
    String banket_date_four,
    String sample,
    String presentation,
    String submit_date,
    int process_times,
    String hotel,
    double buffed_temp_one,
    double buffed_temp_two,
    double buffed_temp_three,
    double buffed_temp_four,
    double buffed_temp_five,
    double buffed_temp_six,
    String buffed_date_one,
    String buffed_date_two,
    String buffed_date_three,
    String buffed_date_four,
    String buffed_date_five,
    String buffed_date_six,
    double cooling_start_temp,
    double cooling_end_temp,
    String cooling_date,
    String section_name,
    String reso_num,
    String first_buffed_status,
    String banket,
    String asset_result,
    double cooling_reheat_temp,
    String cooling_reheat_date,
    String cooling_end_date,
  ) async {
    HPRepo.hotProcessSubmit(
        asset_name,
        user_name,
        quantity,
        first_temperature,
        banket_temperature_one,
        banket_temperature_two,
        banket_temperature_three,
        banket_temperature_four,
        banket_date_one,
        banket_date_two,
        banket_date_three,
        banket_date_four,
        sample,
        presentation,
        submit_date,
        process_times,
        hotel,
        buffed_temp_one,
        buffed_temp_two,
        buffed_temp_three,
        buffed_temp_four,
        buffed_temp_five,
        buffed_temp_six,
        buffed_date_one,
        buffed_date_two,
        buffed_date_three,
        buffed_date_four,
        buffed_date_five,
        buffed_date_six,
        cooling_start_temp,
        cooling_end_temp,
        cooling_date,
        section_name,
        reso_num,
        first_buffed_status,
        banket,
        asset_result,
        cooling_reheat_temp,
        cooling_reheat_date,
        cooling_end_date);
  }
}
